language: node_js # Для сборки нужен будет NodeJS
node_js:
  - stable # Выбираем последню стабильную версию NodeJS
script:
  - npm run prod # Запускаем продакшен-сборку, скрипт из `package.json`
cache:
  directories:
    - "node_modules"
deploy:
  edge:
    branch: v1.8.47
  provider: pages # Используем возможности GithubPages
  skip_cleanup: true # Не чистим рабочую директорию
  # GITHUB_TOKEN — код, обеспечивающий интеграцию Тревиса и Гитхаба.
  # Нужно сгенерировать тут: https://github.com/settings/tokens и добавить в настройки репозитория в Тревисе
  github_token: $GITHUB_TOKEN
  local_dir: dist # название директории, из которой будут отдаваться файлы на сервере
